#include "services/AuthService.h"
#include "database/DatabaseManager.h"

#include <QSqlQuery>
#include <QVariant>
#include <QDateTime>
#include <QCryptographicHash>

QString AuthService::hashPassword(const QString& password) {
    QByteArray hash = QCryptographicHash::hash(
        password.toUtf8(),
        QCryptographicHash::Sha256
        );
    return QString(hash.toHex());
}

bool AuthService::registerUser(const QString& username,
                               const QString& password,
                               const QString& email) {
    // 1. Insert the user row
    QSqlQuery q = DatabaseManager::instance().prepare(
        "INSERT INTO users(username, password_hash, email, acc_creation_date) "
        "VALUES (?, ?, ?, ?)"
        );

    q.addBindValue(username);
    q.addBindValue(hashPassword(password));
    q.addBindValue(email);
    q.addBindValue(QDateTime::currentDateTime().toString(Qt::ISODate));

    if (!DatabaseManager::instance().executePrepared(q))
        return false;

    // 2. Grab the new user's id (auto-incremented by SQLite).
    //    QSqlQuery::lastInsertId() returns the last AUTOINCREMENT value
    //    generated by *this* query — exactly what we want.
    int newUserId = q.lastInsertId().toInt();
    if (newUserId <= 0)
        return false;   // shouldn't happen, but guard anyway

    // 3. Create a default "Main" account for the user.
    //    Without this, transactions can never be saved (they reference account_id).
    QSqlQuery acc = DatabaseManager::instance().prepare(
        "INSERT INTO accounts(user_id, name) VALUES (?, ?)"
        );
    acc.addBindValue(newUserId);
    acc.addBindValue("Main");

    return DatabaseManager::instance().executePrepared(acc);
}

// Bool-only overload — kept for backwards compatibility / quick checks
bool AuthService::login(const QString& username, const QString& password) {
    QSqlQuery q = DatabaseManager::instance().prepare(
        "SELECT password_hash FROM users WHERE username = ?"
        );

    q.addBindValue(username);

    if (!DatabaseManager::instance().executePrepared(q) || !q.next())
        return false;

    QString storedHash = q.value(0).toString();
    return storedHash == hashPassword(password);
}

// Full overload — verifies password AND fills `outUser` on success.
// LoginWindow uses this so it can pass a real User to Dashboard.
bool AuthService::login(const QString& username, const QString& password, User& outUser) {
    QSqlQuery q = DatabaseManager::instance().prepare(
        "SELECT id, username, password_hash, acc_creation_date "
        "FROM users WHERE username = ?"
        );

    q.addBindValue(username);

    if (!DatabaseManager::instance().executePrepared(q) || !q.next())
        return false;

    QString storedHash = q.value(2).toString();
    if (storedHash != hashPassword(password))
        return false;

    outUser.set_id(q.value(0).toInt());
    outUser.set_username(q.value(1).toString());
    outUser.set_passwordHash(storedHash);
    outUser.set_acc_creation_date(QDateTime::fromString(q.value(3).toString(), Qt::ISODate));

    return true;
}

User AuthService::getUserByUsername(const QString& username) {
    User user;   // default-constructed: id == 0, isValid() == false

    QSqlQuery q = DatabaseManager::instance().prepare(
        "SELECT id, username, password_hash, acc_creation_date "
        "FROM users WHERE username = ?"
        );

    q.addBindValue(username);

    if (!DatabaseManager::instance().executePrepared(q) || !q.next())
        return user;   // not found → invalid User

    user.set_id(q.value(0).toInt());
    user.set_username(q.value(1).toString());
    user.set_passwordHash(q.value(2).toString());
    user.set_acc_creation_date(QDateTime::fromString(q.value(3).toString(), Qt::ISODate));

    return user;
}